stages:
  - deploy
  - redeploy


## Code Deploy
# Sync the local copy of the code
deploy_prod:
  stage: deploy
  only:
    - bmac
  before_script:
    - cd /app/pawtucket && cp $PROD_ENV_FILE .env
  script:
    - cd /app/pawtucket
    - git pull
    - source .env
    - docker-compose build --build-arg LOCAL_UID=$LOCAL_UID --build-arg SERVERNAME=$SERVERNAME  
    - docker-compose up -d
  after_script:
    - cd /app/pawtucket && rm .env
  environment:
    name: prod
    url: https://pawtucket.galib.uga.edu
  tags:
    - brown-hosting-shell

